### ISSUE TITLE
Incorrect river cross - Minor bug

### ISSUE THREAD

**Issue by MoroBagg** [moltenwolfcub/Forest-Game#1]
I know you are probably aware of this but when crossing the river in this specific location (as far as I know) it takes you to the center and then when you try crossing again it takes you to the top of the cliff. Minor bug may be larger one in the future.
![issuep1](https://github.com/moltenwolfcub/Forest-Game/assets/131180722/d8644f09-dc94-4fe8-905a-3142ffd0a8ef)
![issuep2](https://github.com/moltenwolfcub/Forest-Game/assets/131180722/8f36c014-7ea6-47ab-822f-8f4e04084ed9)
![issuep3](https://github.com/moltenwolfcub/Forest-Game/assets/131180722/affccb4b-b1ec-4da1-898d-2e654e7a3bf8)

**Comment by moltenwolfcub** [comment]
River jumping is currently very broken. This bug basically occurs as the location to teleport to starts at the world origin (the top of the cliff) and then calculates where it should be set to; however if you are in a river like this situation it can't figure out where you are meant to be so it doesn't change the location from world origin. 

The fact that you get stuck in a river when trying to jump across it is a bug. I am aware of this and it should be fixed shortly

**Comment by MoroBagg** [comment]
Alright cool, just wanted to make it known.
